export default [
  { name: "Milk", expire: "7" },
  { name: "Yogurt", expire: "14" },
  { name: "Cheese", expire: "30" },
  { name: "Shredded Cheese", expire: "14" },
  { name: "Butter", expire: "60" },
  { name: "Cream Cheese", expire: "14" },
  { name: "Sour Cream", expire: "14" },
  { name: "Heavy Cream", expire: "7" },
  { name: "Almond Milk (opened)", expire: "10" },
  { name: "Coconut Milk", expire: "7" },
  { name: "Eggs", expire: "21" },
  { name: "boiled Eggs", expire: "7" },
  { name: "Raw Chicken", expire: "2" },
  { name: "Beef", expire: "3" },
  { name: "Pork", expire: "3" },
  { name: "Fish", expire: "2" },
  { name: "Shrimp", expire: "2" },
  { name: "Clams", expire: "1 day" },
  { name: "Mussels", expire: "1 day" },
  { name: "Lobster", expire: "1 day" },
  { name: "cCooked Chicken", expire: "4" },
  { name: "Cooked Beef", expire: "4" },
  { name: "cooked Pork", expire: "4" },
  { name: "cooked Fish", expire: "3" },
  { name: "Shrimp (cooked)", expire: "3" },
  { name: "Bacon (cooked)", expire: "7" },
  { name: "Ham (cooked)", expire: "7" },
  { name: "Sausage (cooked)", expire: "7" },
  { name: "Cooked Rice", expire: "6" },
  { name: "Cooked Yam", expire: "5" },
  { name: "Cooked Pasta", expire: "5" },
  { name: "Cooked Beans", expire: "5" },
  { name: "Fried Rice", expire: "5" },
  { name: "Jollof Rice", expire: "5" },
  { name: "White Rice", expire: "6" },
  { name: "Coconut Rice", expire: "5" },
  { name: "Porridge (Yam Porridge)", expire: "4" },
  { name: "Vegetable Soup", expire: "4" },
  { name: "Tomato Stew", expire: "5" },
  { name: "Pepper Soup", expire: "4" },
  { name: "Egusi Soup", expire: "4" },
  { name: "Ogbono Soup", expire: "4" },
  { name: "Okra Soup", expire: "4" },
  { name: "Efo Riro (Spinach Stew)", expire: "4" },
  { name: "Groundnut Soup", expire: "5" },
  { name: "Banga Soup (Palm nut soup)", expire: "5" },
  { name: "Chicken Soup", expire: "5" },
  { name: "Beef Stew", expire: "5" },
  { name: "Seafood Gumbo", expire: "4" },
  { name: "Chili (with meat)", expire: "5" },
  { name: "Lasagna", expire: "5" },
  { name: "Shepherd’s Pie", expire: "5" },
  { name: "Macaroni and Cheese", expire: "5" },
  { name: "Chicken Curry", expire: "5" },
  { name: "Curry (Vegetarian)", expire: "5" },
  { name: "Pounded Yam", expire: "3" },
  { name: "Amala", expire: "3" },
  { name: "Eba", expire: "3" },
  { name: "Fufu", expire: "3" },
  { name: "Moi Moi", expire: "5" },
  { name: "Akara (bean cakes)", expire: "2" },
  { name: "Pancake", expire: "3" },
  { name: "Waffles", expire: "3" },
  { name: "Banana", expire: "7" },
  { name: "Apple", expire: "30" },
  { name: "Orange", expire: "30" },
  { name: "Lemon", expire: "30" },
  { name: "Strawberry", expire: "5" },
  { name: "Blueberry", expire: "7" },
  { name: "Raspberry", expire: "3" },
  { name: "Blackberry", expire: "4" },
  { name: "Grapes", expire: "7" },
  { name: "Avocado", expire: "5" },
  { name: "Tomato", expire: "7" },
  { name: "Lettuce", expire: "7" },
  { name: "Spinach", expire: "5" },
  { name: "Kale", expire: "7" },
  { name: "Carrot", expire: "28" },
  { name: "Broccoli", expire: "7" },
  { name: "Cauliflower", expire: "7" },
  { name: "Onion", expire: "30" },
  { name: "Garlic", expire: "90" },
  { name: "Cucumber", expire: "7" },
  { name: "Bell Pepper", expire: "7" },
  { name: "Celery", expire: "14" },
  { name: "Mushrooms", expire: "5" },
  { name: "Zucchini", expire: "7" },
  { name: "Green Beans", expire: "7" },
  { name: "Sweet Potato", expire: "30" },
  { name: "Irish Potato", expire: "60" },
  { name: "Uncooked Rice", expire: "730" },
  { name: "Uncooked Pasta", expire: "730" },
  { name: "Oats", expire: "365" },
  { name: "Flour", expire: "180" },
  { name: "Sugar", expire: "730" },
  { name: "Brown Sugar", expire: "180" },
  { name: "Cereal", expire: "30" },
  { name: "Bread", expire: "5" },
  { name: "Frozen Bread", expire: "90" },
  { name: "Canned Tuna", expire: "3" },
  { name: "Canned Beans", expire: "5" },
  { name: "Tomato Paste", expire: "7" },
  { name: "Tomato Sauce", expire: "5" },
  { name: "Salsa", expire: "14" },
  { name: "Pickles", expire: "90" },
  { name: "Relish", expire: "90" },
  { name: "Pesto", expire: "7" },
  { name: "Jam", expire: "90" },
  { name: "Honey", expire: "730" },
  { name: "Peanut Butter", expire: "180" },
  { name: "Mayonnaise", expire: "60" },
  { name: "Ketchup", expire: "180" },
  { name: "Mustard", expire: "365" },
  { name: "Olive Oil", expire: "540" },
  { name: "Canola Oil", expire: "365" },
  { name: "Vegetable Oil", expire: "365" },
  { name: "Peanuts", expire: "180" },
  { name: "Almonds", expire: "180" },
  { name: "Cashews", expire: "180" },
  { name: "Walnuts", expire: "180" },
  { name: "Chia Seeds", expire: "365" },
  { name: "Flax Seeds", expire: "365" },
  { name: "Sunflower Seeds", expire: "180" },
  { name: "Pumpkin Seeds", expire: "180" },
  { name: "Basil (fresh)", expire: "7" },
  { name: "Cilantro (fresh)", expire: "5" },
  { name: "Parsley (fresh)", expire: "7" },
  { name: "Mint (fresh)", expire: "7" },
  { name: "Rosemary (fresh)", expire: "14" },
  { name: "Thyme (fresh)", expire: "14" },
  { name: "Oregano (fresh)", expire: "14" },
  { name: "Frozen Vegetables", expire: "365" },
  { name: "Frozen Fruits", expire: "365" },
  { name: "Frozen Pizza", expire: "180" },
  { name: "Frozen Chicken Nuggets", expire: "180" },
  { name: "Ice Cream", expire: "90" }
];
